apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
  labels:
    app: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: youknowit-secret-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack-secret
    creationPolicy: Owner
  data:
    - secretKey: webhook-url
      remoteRef:
        key: youknowit/alertmanager/slack
        property: webhook-url
