apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Lielik/YouKnowIt-gitops.git
    targetRevision: HEAD
    path: platform/logging
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
