apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: youknowit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Lielik/YouKnowIt-gitops.git
    targetRevision: HEAD
    path: charts/youknowit
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: youknowit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
